### ISSUE TITLE
Port Forwarding Error

### ISSUE THREAD

**Issue by Magi1053** [kirodotdev/Kiro#130]
### Operating System

win32

### Kiro Version

0.1.0

### Bug Description

The code tunnel exe is missing from the bin folder.

Unable to forward localhost:3000. spawn <USER>\AppData\Local\Programs\Kiro\bin\code-tunnel.exe ENOENT

### Steps to Reproduce

1. Open the bottom panel.
2. Click on the PORTS tab.
3. Click "Forward a Port" button.
4. Enter port to forward

### Expected Behavior

This allows services running on local to be accessible publicly via `https://use.devtunnels.ms/`

### Additional Context

https://learn.microsoft.com/en-us/azure/developer/dev-tunnels/get-started?tabs=windows

**Comment by nadetastic** [comment]
Hi @Magi1053 thank you for opening this issue, we are going to track this as a bug and follow up here with any updates.

**Comment by Lanhubs** [comment]
Error when forwarding the port I was getting spawn

**Comment by AnilMaktala** [comment]
We have implemented significant improvements in recent versions of Kiro. We recommend upgrading to the latest version to benefit from these enhancements. If you continue to experience issues after upgrading, please submit a new issue with detailed information about the problem.

**Comment by Magi1053** [comment]
@AnilMaktala I just installed the latest version and I am still having this exact same bug.

**Comment by Lanhubs** [comment]
How I got over this in my case then was to copy vscode port forwarding source code and paste it inside of the Kiro source code since Kiro is a fork of Vscode and that got me out of this nightmare

**Comment by Magi1053** [comment]
@Lanhubs i have done this but it only works until the next time Kiro updates then it gets removed again.

**Comment by eheimer** [comment]
I also am on the latest version of Kiro, but I'm using Linux.  When I issue the command: `kiro tunnel`, I get the following similar response:

`spawn /usr/share/kiro/bin/kiro-tunnel ENOENT`

when I `find / -name "kiro-tunnel"` it does not exist anywhere.

this suggests the kiro executable knows about the kiro-tunnel executable, it just doesn't exist.

I can issue the `code tunnel` command and it serves up the server just fine.  I am able to remote in.  The problem is this gives me access to the vanilla `code` interface, not the `kiro` interface, which is what I'm looking for.

Version: 0.11.130
VSCode Version: 1.107.1
Commit: 64cdfbdf9e520cbc57cace1e9eeff15ed42f9f05
Date: 2026-04-02T18:49:34.346Z
Electron: 39.6.0
Chromium: 142.0.7444.265
Node.js: 22.22.0
V8: 14.2.231.22-electron.0
OS: Linux x64 6.18.7-76061807-generic
