### ISSUE TITLE
Issue Accessing Kiro After Waitlist Confirmation

### ISSUE THREAD

**Issue by agoutam-mindbody** [kirodotdev/Kiro#1784]
### Before opening, please confirm:

- [x] I have [searched for duplicate or closed issues](https://github.com/kirodotdev/Kiro/issues?q=is%3Aissue+)

### Operating System

win32

### Kiro Version

0.1.42

### Bug Description

Hi,

I recently received an email notifying me that I’ve been removed from the waitlist. Following that, I downloaded Kiro and signed in using the AWS Builder authentication method with the same email ID.

However, I wasn’t prompted to enter the access code provided in the email. Now, whenever I try to access Kiro Chat, I see the message: "Kiro access not available for this account."

Could you please assist me in resolving this issue?

Thank you.
Akhilesh Goutam

### Steps to Reproduce

Download Kiro
Used AWS Builder auth method
Sign into IDE
Try and access kiro chat

### Expected Behavior

Expected to access Kiro chat

### Conversation ID

5acfdfdf-c166-47c7-bffb-fe47489b66cf
4c780ea6-f03b-4428-bf44-5792c0170a5a

**Comment by wxddegithub** [comment]
Has it been resolved

**Comment by cpx-97** [comment]
同问

**Comment by agoutam-mindbody** [comment]
> Has it been resolved

Not yet. Still getting the same "Kiro access not available for this account."

**Comment by RynoRocks** [comment]
Part of the Kiro hackathon, I also downloaded, asked chat where the Kiro access code page was, and it replied with, "Kiro access not available for this account."  Has anyone entered their access code yet?

**Comment by Jay2113** [comment]
Hi everyone! 👋 If you've received an access code via email, please sign in using either Google or GitHub authentication. These are the only authentication methods that work with access codes. Thanks for your patience!

**Comment by RynoRocks** [comment]
Thanks, Jay. I have done so. Exactly where is the code to be entered?

**Comment by redballoon** [comment]
I originally signed in with AWS Builder Id and that didn't work. I tried signing out and using Github account like suggested but I get redirected after connecting to my account to a page that says "Error: Failure from identity provider: invalid_request: Something went wrong. Please try again."

**Comment by cayhorstmann** [comment]
I just attempted to sign in with Google and Github, and the access code I got by email was rejected as invalid.

**Comment by Rowan-Paul** [comment]
I have gotten the access code via email, downloaded and tried logging in using Google & GitHub but keep getting the same invalid access code. I am using the same email for logging in as I have received the email with.

<img width="2476" height="1964" alt="Image" src="https://github.com/user-attachments/assets/cf19a28c-9674-4d28-b917-46b24cf691c6" />

**Comment by nickboot** [comment]
I used the same email address and access code but failed to log in from another computer.

**Comment by njisaf** [comment]
I received three access codes simultaneously (to the same email). None of them have worked; I have attempted using both Google and Github logins.

**Comment by WickedCPU** [comment]
Same here, just received the access code and attempted logging in with gmail (same one I joined the waitlist with) and github to use the code and get "Invalid access code." on both.

**Comment by kopenkinda** [comment]
+1, nevermind after spamming validate a few times it worked :D

**Comment by keviunknown** [comment]
just remove the blank space at start of the code and it will work.

**Comment by jelenv** [comment]
> just remove the blank space at start of the code and it will work.

fixed my issue ... thanks a lot

**Comment by Rowan-Paul** [comment]
Typing it manually from the email, still no luck. Really annoying there is no solution yet, seems like a pretty big problem.

**Comment by EmbroiderSnow** [comment]
> just remove the blank space at start of the code and it will work.

Thanks bro. It works.

**Comment by gianmaria** [comment]
> > just remove the blank space at start of the code and it will work.
> 
> Thanks bro. It works.

Unbelievable! When you copy the code straight from the email, there's a new line at the beginning that gets converted to a space, which prevents you from validating the code 😖

**Comment by foeffa** [comment]
> > just remove the blank space at start of the code and it will work.
> 
> Thanks bro. It works.

Omg ... this was my issue. Thanks bro

**Comment by ueno-cmd** [comment]
**Environment:**
- OS: Linux Ubuntu x64 6.14.0-27-generic
- Kiro Version: 0.2.13 (latest)
- VSCode Version: 1.94.0
- Date: August 20, 2025

**Issue:**
Experiencing "Invalid access code" error despite following all official documentation and troubleshooting steps.

**Steps Taken:**
1. ✅ Downloaded latest Kiro version (0.2.13) 
2. ✅ GitHub authentication completed successfully
3. ✅ Using correct email address (same as waitlist registration)
4. ✅ Access code from official Kiro team email
5. ✅ Followed troubleshooting guide at kiro.dev/docs/getting-started/waitlist-access-codes/

**Current Status:**
- GitHub OAuth authentication: ✅ Successful
- Access code entry: ❌ "Invalid access code" error
- Same issue persists across multiple attempts over several days

**Concern:**
Access code may have expiration date. Request urgent assistance or new access code issuance.

**Additional Notes:**
This appears to be the same systemic issue reported by multiple users in this thread. Latest version and proper authentication methods are being used, suggesting server-side access management issue.

**Additional Information:**
- User location: Japan
- If needed, I can provide additional details in Japanese or through Japanese support channels.

Thank you for your assistance with this urgent matter.

**Comment by ueno-cmd** [comment]
**Update - Issue Resolved**

Sorry for the confusion! I discovered the root cause of my "Invalid access code" error.

**Root Cause:** 
When copying the access code from the email, there was an invisible leading whitespace character that I didn't notice. This caused the authentication to fail with "Invalid access code" error.

**Solution:**
Manually typed the access code (or carefully removed leading/trailing spaces) and authentication worked successfully.

**For other users experiencing this issue:**
Please check for invisible whitespace characters when copying access codes from emails. Try:
1. Manually typing the code instead of copy-paste
2. Paste into a text editor first to check for extra spaces
3. Ensure no leading/trailing whitespace

Authentication is now working perfectly on Kiro 0.2.13 with GitHub auth.

Thank you and sorry for the noise!

**Note from Japan:**
笑いたければ笑ってください - Feel free to laugh if you want! 😅

Sometimes the simplest issues are the hardest to spot. Hope this helps other users avoid the same mistake.

> **Environment:**
> 
>     * OS: Linux Ubuntu x64 6.14.0-27-generic
> 
>     * Kiro Version: 0.2.13 (latest)
> 
>     * VSCode Version: 1.94.0
> 
>     * Date: August 20, 2025
> 
> 
> **Issue:** Experiencing "Invalid access code" error despite following all official documentation and troubleshooting steps.
> 
> **Steps Taken:**
> 
>     1. ✅ Downloaded latest Kiro version (0.2.13)
> 
>     2. ✅ GitHub authentication completed successfully
> 
>     3. ✅ Using correct email address (same as waitlist registration)
> 
>     4. ✅ Access code from official Kiro team email
> 
>     5. ✅ Followed troubleshooting guide at kiro.dev/docs/getting-started/waitlist-access-codes/
> 
> 
> **Current Status:**
> 
>     * GitHub OAuth authentication: ✅ Successful
> 
>     * Access code entry: ❌ "Invalid access code" error
> 
>     * Same issue persists across multiple attempts over several days
> 
> 
> **Concern:** Access code may have expiration date. Request urgent assistance or new access code issuance.
> 
> **Additional Notes:** This appears to be the same systemic issue reported by multiple users in this thread. Latest version and proper authentication methods are being used, suggesting server-side access management issue.
> 
> **Additional Information:**
> 
>     * User location: Japan
> 
>     * If needed, I can provide additional details in Japanese or through Japanese support channels.
> 
> 
> Thank you for your assistance with this urgent matter.

**Comment by srav78** [comment]
I have a paid Kiro subscription associated with my AWS builder ID with plenty of unused credits. Hence I am logged in with the builder ID on Ubuntu 22.04 platform. The Kiro version is the latest one. I am getting the same error. How do I get past it? Logging in using another account is not ideal since I need to use the credits associated with the paid account

**Comment by Alkush-Pipania** [comment]
+1 , it works after some time

**Comment by advaitku** [comment]
I am still getting the "Invalid access code."

1. Tried manually typing the code (no whitespaces)
2. Latest version of Kiro
3. Login via Github and Gmail tried both
4. spammed the Validate button a few times

**Comment by peterdays** [comment]
> just remove the blank space at start of the code and it will work.

this was gold, thank you sir

**Comment by datfinesoul** [comment]
I can't get the screen to show where I can enter the access code.  Logging in with my GitHub account.

**Comment by AnilMaktala** [comment]
Thank you for taking the time to report this. This issue has had no activity for over 90 days and the areas it relates to have been significantly reworked in newer versions of Kiro.

We're closing this as stale, but if you're still experiencing the issue on the latest version, please don't hesitate to open a new issue — we're happy to take another look.
