### ISSUE TITLE
Linux users cannot upgrade Kiro client

### ISSUE THREAD

**Issue by wysow** [kirodotdev/Kiro#693]
### Before opening, please confirm:

- [x] I have [searched for duplicate or closed issues](https://github.com/kirodotdev/Kiro/issues?q=is%3Aissue+)

### Operating System

Ubuntu 24.04

### Kiro Version

0.1.6

### Bug Description

Hello there! Everything is in the title.

### Steps to Reproduce

1. Click on `dowload update` option in Kiro IDE
2. redirected to kiro.dev website without an option to download the update if we are already a registered user.

### Expected Behavior

Find a way to reach a dowload link to update Kiro IDE somehow.

**Comment by olamedia** [comment]
Yep, updates are not possible :/

**Comment by seekersingh** [comment]
Same issue. Can see the notification for the update but clicking on "Download Update" takes to kiro.dev without any actual download.

**Comment by Syl204269** [comment]
I have a new macbook. I would like to install Kiro on it, but I can't download the install files for M1 macbook (last week I have downloaded the Intel version).

I hope we will have a solution soon as I will have to return my old intel mac :(

**Comment by jamesjhonatan123** [comment]
Yeah, when I click to update I get redirected to join the waitlist. But I downloaded Kiro before there was a waitlist.

**Comment by matusbielik** [comment]
Same for me on Debian, installed from this Deb package `202507161954-distro-linux-x64.deb` but can't update, I'm redirected to website. It looks we are locked-out of updates on Linux, as it is a problem in currently installed version but the authors don't want to publicly open Kiro for everyone.

**Comment by Jay2113** [comment]
Hi everyone, we are aware of the issue where Linux users cannot upgrade their Kiro client version. We are actively working on this and it is one of our highest priorities. Thanks for your continued patience, and we will keep this thread updated with any progress.

**Comment by mikzzai** [comment]
The simplest solution is to implement a user account system with Google login, where users can download the latest version.

**Comment by johan--** [comment]
Any feedback on this issue? Running on Ubuntu, one of the day one Linux users to join...

**Comment by v3ct0rm4n** [comment]
Any status updates or work arounds yet? (linux mint)

**Comment by jamesjhonatan123** [comment]
To use the latest version, I uninstalled the current version from my PC and reinstalled it using the installer I had. This way, the latest version was installed.

**Comment by anthraxau** [comment]
Most Linux users were only given the option to download the tarball. No installer was provided.

**Comment by tmkmch** [comment]
Workaround for debian distros (Ubuntu etc.). Go to AUR  https://aur.archlinux.org/packages/kiro-bin

Check sources. There will be the newest released version. If you want to download the Deb package just change the  extension from tar.gz to deb in the link.

**Comment by getswyft** [comment]
> Workaround for debian distros (Ubuntu etc.). Go to AUR https://aur.archlinux.org/packages/kiro-bin
> 
> Check sources. There will be the newest released version. If you want to download the Deb package just change the extension from tar.gz to deb in the link.

i gave that a try, but getting access denied.

**Comment by tmkmch** [comment]
> > Workaround for debian distros (Ubuntu etc.). Go to AUR https://aur.archlinux.org/packages/kiro-bin
> > 
> > Check sources. There will be the newest released version. If you want to download the Deb package just change the extension from tar.gz to deb in the link.
> 
> i gave that a try, but getting access denied.

It works. Just changed like that:

https://prod.download.desktop.kiro.dev/releases/202507260047--distro-linux-x64-deb/202507260047-distro-linux-x64.deb
 
You need to change all places with tar.gz.

**Comment by v3ct0rm4n** [comment]
> Workaround for debian distros (Ubuntu etc.). Go to AUR https://aur.archlinux.org/packages/kiro-bin
> 
> Check sources. There will be the newest released version. If you want to download the Deb package just change the extension from tar.gz to deb in the link.

Thank you! It worked

**Comment by Jay2113** [comment]
Hey everyone 👋, you can now download the latest Linux build from our downloads page: https://kiro.dev/downloads/.

**Comment by thamam** [comment]
Do you still need to sign up through the waiting list first? I'm having
issues with the authentication step.

**Comment by anthraxau** [comment]
No issues were encountered when downloading the new version from the Downloads page. If you're having problems authenticating, you may not already be a user and need to wait for the next run of the waitlist.



> Do you still need to sign up through the waiting list first? I'm having
> issues with the authentication step.
> […](#)
>

**Comment by thamam** [comment]
Got it. Thanks!

**Comment by mbonig** [comment]
Why do the other platforms get an auto-update but Linux requires a manual download and install step?

**Comment by gustojs** [comment]
Can you please confirm the way this issue was resolved and completed?

Was it fixed and now Linux users can use the internal Kiro updater?
Or was it determined that a manual download is the way to install on Linux?

Because even a week ago people on Discord were reporting they get redirected to waitlist when they try to update on Linux.

Also, if it wasn't resolved back in August, does it work now that the waitlist is over?

Thanks

**Comment by kienbui1995** [comment]
I really want you to review it carefully because it is not resolved because I clicked update but it did not have any response
